import 'package:flutter/material.dart';
import 'package:flutterapp/chatapp/generatedchatwidget/generated/GeneratedFrame211Widget.dart';
import 'package:flutterapp/chatapp/generatedchatwidget/generated/GeneratedFrame229Widget.dart';
import 'package:flutterapp/chatapp/generatedchatwidget/generated/GeneratedVectorWidget1.dart';
import 'package:flutterapp/chatapp/generatedchatwidget/generated/GeneratedFrame111Widget.dart';
import 'package:flutterapp/chatapp/generatedchatwidget/generated/GeneratedFrame226Widget.dart';
import 'package:flutterapp/chatapp/generatedchatwidget/generated/GeneratedFrame227Widget.dart';
import 'package:flutterapp/chatapp/generatedchatwidget/generated/GeneratedVector44Widget.dart';
import 'package:flutterapp/chatapp/generatedchatwidget/generated/GeneratedFrame225Widget.dart';
import 'package:flutterapp/chatapp/generatedchatwidget/generated/GeneratedFrame228Widget.dart';

/* Frame chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 253, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 392.0,
                height: 72.0,
                child: GeneratedFrame211Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 381.0,
                height: 113.0,
                child: GeneratedFrame226Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 113.0,
                child: GeneratedFrame225Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 113.0,
                child: GeneratedFrame227Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 113.0,
                child: GeneratedFrame228Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 692.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 113.0,
                child: GeneratedFrame229Widget(),
              ),
              Positioned(
                left: 25.5,
                top: 161.5,
                right: null,
                bottom: null,
                width: 371.5,
                height: 0.0,
                child: GeneratedVector44Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 9.879999160766602,
                height: 16.0,
                child: GeneratedVectorWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 833.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 63.0,
                child: GeneratedFrame111Widget(),
              )
            ]),
      ),
    ));
  }
}
