import 'package:flutter/material.dart';
import 'package:flutterapp/profileapp/generatedprofilewidget/generated/GeneratedFrame111Widget.dart';
import 'package:flutterapp/profileapp/generatedprofilewidget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/profileapp/generatedprofilewidget/generated/GeneratedEllipse63Widget.dart';
import 'package:flutterapp/profileapp/generatedprofilewidget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/profileapp/generatedprofilewidget/generated/GeneratedFrame2Widget3.dart';
import 'package:flutterapp/profileapp/generatedprofilewidget/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/profileapp/generatedprofilewidget/generated/GeneratedFrame341Widget.dart';

/* Frame profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 253, 255),
                ),
              ),
              Positioned(
                left: 129.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 142.0,
                child: GeneratedEllipse63Widget(),
              ),
              Positioned(
                left: 236.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 31.913043975830078,
                child: GeneratedFrame341Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 78.0,
                child: GeneratedFrame5Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 78.0,
                child: GeneratedFrame6Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 78.0,
                child: GeneratedFrame7Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 689.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 50.0,
                child: GeneratedFrame2Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 833.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 63.0,
                child: GeneratedFrame111Widget(),
              )
            ]),
      ),
    ));
  }
}
