import 'package:flutter/material.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedInminsWidget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedTextWidget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedFrame129Widget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedTimer1Widget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedFrame203Widget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedFrame193Widget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedSettimeoutWidget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedFrame192Widget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedFrame111Widget.dart';
import 'package:flutterapp/timerapp/generatedsettimewidget/generated/GeneratedFrame194Widget.dart';

/* Frame set time
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettimeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 253, 255),
                ),
              ),
              Positioned(
                left: 77.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 59.0,
                child: GeneratedSettimeoutWidget(),
              ),
              Positioned(
                left: 223.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 71.0,
                child: GeneratedFrame192Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 71.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 122.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 2.0,
                height: 21.0,
                child: GeneratedTextWidget(),
              ),
              Positioned(
                left: 204.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 29.0,
                child: GeneratedFrame194Widget(),
              ),
              Positioned(
                left: 307.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 71.0,
                child: GeneratedFrame193Widget(),
              ),
              Positioned(
                left: 178.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 21.0,
                child: GeneratedInminsWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 353.0,
                height: 30.0,
                child: GeneratedFrame203Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 50.0,
                child: GeneratedFrame2Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 9.879999160766602,
                height: 16.0,
                child: GeneratedVectorWidget(),
              ),
              Positioned(
                left: 107.0,
                top: 74.0,
                right: 107.0,
                bottom: null,
                width: null,
                height: 200.0,
                child: GeneratedTimer1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: 63.0,
                child: GeneratedFrame111Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 88.875,
                height: 21.875,
                child: GeneratedFrame129Widget(),
              )
            ]),
      ),
    ));
  }
}
